# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'IDODemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # IDOSDK
  pod 'IDOSDK' , :path => '../IDOSDK/'
  
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SVProgressHUD'

end
