# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

# Comment the next line if you don't want to use dynamic frameworks
#source 'https://cdn.cocoapods.org/'
source 'https://gitee.com/idoosmart/IDOSmartSpec.git'
use_frameworks!
inhibit_all_warnings!

target 'IDODemoFull' do
  pod 'IDOSDK-full', '~> 4.0.24'
end

target 'IDODemoLite' do
  pod 'IDOSDK-lite', '~> 4.0.24'
end


pod 'SnapKit'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SVProgressHUD'
pod 'ReachabilitySwift'
pod 'SSZipArchive'
