# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# Comment the next line if you don't want to use dynamic frameworks
source 'https://cdn.cocoapods.org/'
source 'https://github.com/idoosmart/IDOSmartSpec.git'
use_frameworks!
inhibit_all_warnings!

target 'IDODemoFull' do
  pod 'IDOSDK-full', '~> 4.0.39'
end

target 'IDODemoLite' do
  pod 'IDOSDK-lite', '~> 4.0.39'
end


pod 'SnapKit'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SVProgressHUD'
pod 'ReachabilitySwift'
pod 'SSZipArchive'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
