import Foundation

// MARK: - Strings

// This file is auto-generated by scripts/sync_strings.py
// Do not edit manually. Run `python3 scripts/sync_strings.py` to regenerate.

enum L10n {

    // MARK: - Common
    static var cancelFull: String { String(localized: "Cancel") }
    /// Cancel
    static var cancel: String { String(localized: "cancel") }
    /// The app is exiting, do you want to continue?
    static var exitApp: String { String(localized: "exit_app") }
    /// Refresh
    static var refresh: String { String(localized: "refresh") }
    /// Supported
    static var supported: String { String(localized: "supported") }
    /// Unsupported
    static var unsupported: String { String(localized: "unsupported") }

    // MARK: - EPO
    /// Start Epo Upgrade
    static var epoStart: String { String(localized: "epo_start") }
    /// Stop Epo Upgrade
    static var epoStop: String { String(localized: "epo_stop") }

    // MARK: - Bluetooth
    /// Bluetooth is off
    static var bleOff: String { String(localized: "ble_off") }
    /// Fast config failed, need to reconnect
    static var fastconfigFail: String { String(localized: "fastconfig_fail") }
    /// If the mobile phone location permission is not authorized, the watch will not be able to quickly locate the phone.
    static var gpsTips: String { String(localized: "gps_tips") }
    /// Pairing is abnormal, you need to manually ignore the device (Settings-Bluetooth-Find Device-"!")-Ignore this device
    static var needIgnorePair: String { String(localized: "need_ignore_pair") }
    /// This device does not support
    static var nonsupport: String { String(localized: "nonsupport") }
    /// On fast config...
    static var onFastconfig: String { String(localized: "on_fastconfig") }

    // MARK: - System
    /// Incoming call reminder
    static var callRemind: String { String(localized: "call_remind") }
    /// fetch failed
    static var fetchFail: String { String(localized: "fetch_fail") }
    /// Main switch
    static var mainSwitch: String { String(localized: "main_switch") }
    /// Note: For iOS 13 and above, you need to turn on [Share System Notifications] in the phone system.
    static var systemNotifyTips: String { String(localized: "system_notify_tips") }

    // MARK: - Notification
    /// allowed
    static var notifyAllowed: String { String(localized: "notify_allowed") }
    /// disabled
    static var notifyDisabled: String { String(localized: "notify_disabled") }
    /// Notify settings
    static var notifySettings: String { String(localized: "notify_settings") }
    /// silent
    static var notifySilent: String { String(localized: "notify_silent") }

    // MARK: - Get Operations
    /// Get event number for activity switch
    static var getActivitySwitch: String { String(localized: "getActivitySwitch") }
    /// App gets the alarm of ble
    static var getAlarm: String { String(localized: "getAlarm") }
    /// Get firmware algorithm file information (ACC/GPS)
    static var getAlgFileInfo: String { String(localized: "getAlgFileInfo") }
    /// Get event number for all health monitoring switches
    static var getAllHealthSwitchState: String { String(localized: "getAllHealthSwitchState") }
    /// Operation of applet information (obtain, start, delete)
    static var getAppletControl: String { String(localized: "getAppletControl") }
    /// Get battery information event number
    static var getBatteryInfo: String { String(localized: "getBatteryInfo") }
    /// Get Battery Reminder Switch
    static var getBatteryReminderSwitch: String { String(localized: "getBatteryReminderSwitch") }
    /// Get Bike Lock List
    static var getBikeLockList: String { String(localized: "getBikeLockList") }
    /// Getting firmware local beep file information for V3
    static var getBleBeep: String { String(localized: "getBleBeep") }
    /// Get Firmware Song Names and Folders
    static var getBleMusicInfo: String { String(localized: "getBleMusicInfo") }
    /// Get blood pressure algorithm version information event number
    static var getBpAlgVersion: String { String(localized: "getBpAlgVersion") }
    /// Get BT connected phone model
    static var getBtConnectPhoneModel: String { String(localized: "getBtConnectPhoneModel") }
    /// Get bt bluetooth name
    static var getBtName: String { String(localized: "getBtName") }
    /// Query BT pairing switch, connection, A2DP connection, HFP connection status (Only Supported on devices with BT Bluetooth) event number
    static var getBtNotice: String { String(localized: "getBtNotice") }
    /// Get firmware local contact file modification time event number
    static var getContactReviseTime: String { String(localized: "getContactReviseTime") }
    /// Get device information
    static var getDeviceInfo: String { String(localized: "getDeviceInfo") }
    /// Get device log state event number
    static var getDeviceLogState: String { String(localized: "getDeviceLogState") }
    /// Get Device Name
    static var getDeviceName: String { String(localized: "getDeviceName") }
    /// Get Download Language Support
    static var getDownloadLanguage: String { String(localized: "getDownloadLanguage") }
    /// Get error record
    static var getErrorRecord: String { String(localized: "getErrorRecord") }
    /// Get Find Phone Switch
    static var getFindPhoneSwitch: String { String(localized: "getFindPhoneSwitch") }
    /// Get Font Library Information event number
    static var getFlashBinInfo: String { String(localized: "getFlashBinInfo") }
    /// Get function table information
    static var getFunctionTable: String { String(localized: "getFunctionTable") }
    /// Get GPS Information event number
    static var getGpsInfo: String { String(localized: "getGpsInfo") }
    /// Get GPS Status event number
    static var getGpsStatus: String { String(localized: "getGpsStatus") }
    /// Get User Habit Information
    static var getHabitInfo: String { String(localized: "getHabitInfo") }
    /// Get heart rate mode
    static var getHeartMode: String { String(localized: "getHeartMode") }
    /// Get HID Information
    static var getHidInfo: String { String(localized: "getHidInfo") }
    /// Get Hot Start Parameters
    static var getHotStartParam: String { String(localized: "getHotStartParam") }
    /// Get Language Library List
    static var getLanguageLibrary: String { String(localized: "getLanguageLibrary") }
    /// Get Set Calorie/Distance/Mid-High Sport Time Goal event number
    static var getMainSportGoal: String { String(localized: "getMainSportGoal") }
    /// Get Supported Menu List
    static var getMenuList: String { String(localized: "getMenuList") }
    /// Get Menu List V3
    static var getMenuListV3: String { String(localized: "getMenuListV3") }
    /// Get MTU Information event number
    static var getMtuInfo: String { String(localized: "getMtuInfo") }
    /// Get Do Not Disturb mode status event number
    static var getNotDisturbStatus: String { String(localized: "getNotDisturbStatus") }
    /// Get notification center status event number
    static var getNoticeStatus: String { String(localized: "getNoticeStatus") }
    /// Get Pet Information
    static var getPetInfo: String { String(localized: "getPetInfo") }
    /// Get schedule reminder
    static var getScheduleReminder: String { String(localized: "getScheduleReminder") }
    /// Get screen brightness event number
    static var getScreenBrightness: String { String(localized: "getScreenBrightness") }
    /// Get Smart Heart Rate Mode
    static var getSmartHeartRateMode: String { String(localized: "getSmartHeartRateMode") }
    /// Get Device SN
    static var getSn: String { String(localized: "getSn") }
    /// Get SpO2 Switch
    static var getSpo2Switch: String { String(localized: "getSpo2Switch") }
    /// Get sports list
    static var getSportsTypeV3: String { String(localized: "getSportsTypeV3") }
    /// Get daily step goal event number
    static var getStepGoal: String { String(localized: "getStepGoal") }
    /// Get Stress Switch
    static var getStressSwitch: String { String(localized: "getStressSwitch") }
    /// Get Stress Value
    static var getStressVal: String { String(localized: "getStressVal") }
    /// Get maximum number of settings supported by firmware event number
    static var getSupportMaxSetItemsNum: String { String(localized: "getSupportMaxSetItemsNum") }
    /// Get non-deletable menu list in firmware event number
    static var getUnerasableMeunList: String { String(localized: "getUnerasableMeunList") }
    /// Get Unit event number
    static var getUnit: String { String(localized: "getUnit") }
    /// Get unread app reminder switch event number
    static var getUnreadAppReminder: String { String(localized: "getUnreadAppReminder") }
    /// Get wrist up gesture data event number
    static var getUpHandGesture: String { String(localized: "getUpHandGesture") }
    /// Get device update status event number
    static var getUpdateStatus: String { String(localized: "getUpdateStatus") }
    /// Obtain the version of the embedded SDK, heart rate library, sleep library, step-counting library, wrist-lift gesture library, and PCB version number.
    static var getVersionInfo: String { String(localized: "getVersionInfo") }
    /// Get walk reminder event number
    static var getWalkRemind: String { String(localized: "getWalkRemind") }
    /// Get Watch Dial ID
    static var getWatchDialId: String { String(localized: "getWatchDialId") }
    /// Get Screen Information
    static var getWatchDialInfo: String { String(localized: "getWatchDialInfo") }
    /// Getting watch face list for V2
    static var getWatchListV2: String { String(localized: "getWatchListV2") }
    /// Getting watch face list for V3 (New)
    static var getWatchListV3: String { String(localized: "getWatchListV3") }

    // MARK: - Set Operations
    /// Factory reset
    static var factoryReset: String { String(localized: "factoryReset") }
    /// Control find device start
    static var findDeviceStart: String { String(localized: "findDeviceStart") }
    /// Control find device stop
    static var findDeviceStop: String { String(localized: "findDeviceStop") }
    /// Music control event number
    static var musicControl: String { String(localized: "musicControl") }
    /// Notification message reminder event number
    static var noticeMessageV3: String { String(localized: "noticeMessageV3") }
    /// Start taking photos (app -> ble)
    static var photoStart: String { String(localized: "photoStart") }
    /// Stop taking photos (app -> ble)
    static var photoStop: String { String(localized: "photoStop") }
    /// Reboot device
    static var reboot: String { String(localized: "reboot") }
    /// Getting Alarms for V3APP Devices
    static var setAlarm: String { String(localized: "setAlarm") }
    /// Set Algorithm Sensor Config
    static var setAlgorithmRawDataSensorConfig: String { String(localized: "setAlgorithmRawDataSensorConfig") }
    /// Set App Base Info
    static var setAppBaseInfo: String { String(localized: "setAppBaseInfo") }
    /// Operation of applet information (obtain, start, delete)
    static var setAppletControl: String { String(localized: "setAppletControl") }
    /// Set Bike Lock List
    static var setBikeLockList: String { String(localized: "setBikeLockList") }
    /// CGM：设置密钥与设备名
    static var setCgmKeyAndDevice: String { String(localized: "setCgmKeyAndDevice") }
    /// CGM：删除密钥与设备名
    static var deleteCgmKeyAndDevice: String { String(localized: "deleteCgmKeyAndDevice") }
    /// CGM：连接
    static var connectCgm: String { String(localized: "connectCgm") }
    /// CGM：断开
    static var disconnectCgm: String { String(localized: "disconnectCgm") }
    /// Set phone volume for device event number
    static var setBleVoice: String { String(localized: "setBleVoice") }
    /// Send Blood Glucose Data V01
    static var setBloodGlucoseDataV01: String { String(localized: "setBloodGlucoseDataV01") }
    /// Set body power switch event number
    static var setBodyPowerTurn: String { String(localized: "setBodyPowerTurn") }
    /// Blood Pressure Calibration Control
    static var setBpCalControlV3: String { String(localized: "setBpCalControlV3") }
    /// Blood pressure calibration event number
    static var setBpCalibration: String { String(localized: "setBpCalibration") }
    /// Blood pressure measurement event number
    static var setBpMeasurement: String { String(localized: "setBpMeasurement") }
    /// Set Call Quick Reply On/Off
    static var setCallQuickReplyOnOff: String { String(localized: "setCallQuickReplyOnOff") }
    /// Set calorie and distance goal (Set daily three rings)
    static var setCalorieDistanceGoal: String { String(localized: "setCalorieDistanceGoal") }
    /// Set Time
    static var setDateTime: String { String(localized: "setDateTime") }
    /// Set the default messaging app list
    static var setDefaultMsgList: String { String(localized: "setDefaultMsgList") }
    /// Display mode event number
    static var setDisplayMode: String { String(localized: "setDisplayMode") }
    /// Set Drink Water Reminder
    static var setDrinkWaterRemind: String { String(localized: "setDrinkWaterRemind") }
    /// Set During Exercise Reminder
    static var setDuringExercise: String { String(localized: "setDuringExercise") }
    /// Set Find Phone
    static var setFindPhone: String { String(localized: "setFindPhone") }
    /// Fitness Guidance Event
    static var setFitnessGuidance: String { String(localized: "setFitnessGuidance") }
    /// Control GPS event number
    static var setGpsControl: String { String(localized: "setGpsControl") }
    /// Set left or right hand
    static var setHand: String { String(localized: "setHand") }
    /// Set Hand Washing Reminder Event
    static var setHandWashingReminder: String { String(localized: "setHandWashingReminder") }
    /// Set heart rate mode
    static var setHeartMode: String { String(localized: "setHeartMode") }
    /// Set heart rate interval
    static var setHeartRateInterval: String { String(localized: "setHeartRateInterval") }
    /// Menstrual historical data delivery event number
    static var setHistoricalMenstruation: String { String(localized: "setHistoricalMenstruation") }
    /// Set hot start parameters
    static var setHotStartParam: String { String(localized: "setHotStartParam") }
    /// V3 Setting the Name of a Sports City event number
    static var setLongCityNameV3: String { String(localized: "setLongCityNameV3") }
    /// Sitting Reminders
    static var setLongSit: String { String(localized: "setLongSit") }
    /// Set Lost Find Event
    static var setLostFind: String { String(localized: "setLostFind") }
    /// Setting and Query Sorting of Main UI Controls
    static var setMainUISortV3: String { String(localized: "setMainUISortV3") }
    /// Set menstruation
    static var setMenstruation: String { String(localized: "setMenstruation") }
    /// Set Menstruation Reminder
    static var setMenstruationRemind: String { String(localized: "setMenstruationRemind") }
    /// Set Menu List
    static var setMenuList: String { String(localized: "setMenuList") }
    /// Set Menu List V3
    static var setMenuListV3: String { String(localized: "setMenuListV3") }
    /// Set Music On/Off Event
    static var setMusicOnOff: String { String(localized: "setMusicOnOff") }
    /// Operation for songs or folders event
    static var setMusicOperate: String { String(localized: "setMusicOperate") }
    /// Set Do Not Disturb
    static var setNotDisturb: String { String(localized: "setNotDisturb") }
    /// V3 dynamic notification message event number
    static var setNoticeAppName: String { String(localized: "setNoticeAppName") }
    /// Setting Notification Status for a Single App
    static var setNoticeMessageState: String { String(localized: "setNoticeMessageState") }
    /// Set Notification Center Event (Fully closed)
    static var setNoticeStatusAllOff: String { String(localized: "setNoticeStatusAllOff") }
    /// Set Notification Center Event (Fully open)
    static var setNoticeStatusAllOn: String { String(localized: "setNoticeStatusAllOn") }
    /// Set Notification Center Event (Bt pair)
    static var setNoticeStatusBtPair: String { String(localized: "setNoticeStatusBtPair") }
    /// Notification app status setting event
    static var setNotificationStatus: String { String(localized: "setNotificationStatus") }
    /// Set the one-touch calling event number
    static var setOnekeySOS: String { String(localized: "setOnekeySOS") }
    /// Stop Find Phone
    static var setOverFindPhone: String { String(localized: "setOverFindPhone") }
    /// Respiration rate switch setting event
    static var setRRespiRateTurn: String { String(localized: "setRRespiRateTurn") }
    /// Schedule Reminder
    static var setSchedulerReminder: String { String(localized: "setSchedulerReminder") }
    /// Scientific sleep switch setting event
    static var setScientificSleepSwitch: String { String(localized: "setScientificSleepSwitch") }
    /// Set screen brightness
    static var setScreenBrightness: String { String(localized: "setScreenBrightness") }
    /// App issued running plan (exercise plan) event number
    static var setSendRunPlan: String { String(localized: "setSendRunPlan") }
    /// Set shortcut
    static var setShortcut: String { String(localized: "setShortcut") }
    /// Set Simple Heart Rate Zone
    static var setSimpleHeartRateZone: String { String(localized: "setSimpleHeartRateZone") }
    /// Set sleep period event
    static var setSleepPeriod: String { String(localized: "setSleepPeriod") }
    /// Set SpO2 switch event
    static var setSpo2Switch: String { String(localized: "setSpo2Switch") }
    /// Set and Query 100 Sports Sorting
    static var setSport100Sort: String { String(localized: "setSport100Sort") }
    /// Set exercise goal event
    static var setSportGoal: String { String(localized: "setSportGoal") }
    /// Set sport mode select event number
    static var setSportModeSelect: String { String(localized: "setSportModeSelect") }
    /// Set Sport Mode Sorting
    static var setSportModeSort: String { String(localized: "setSportModeSort") }
    /// Set and Query Sports Sub-item Data Sorting
    static var setSportParamSort: String { String(localized: "setSportParamSort") }
    /// Set Sport Screen Items
    static var setSportScreen: String { String(localized: "setSportScreen") }
    /// Set Sporting Remind Setting
    static var setSportingRemindSetting: String { String(localized: "setSportingRemindSetting") }
    /// Modify the sports list (sort/delete/add)
    static var setSportsTypeV3: String { String(localized: "setSportsTypeV3") }
    /// Set Stress Calibration Event Code
    static var setStressCalibration: String { String(localized: "setStressCalibration") }
    /// Set stress switch
    static var setStressSwitch: String { String(localized: "setStressSwitch") }
    /// Synchronization Protocol Bluetooth Call Common Contacts
    static var setSyncContact: String { String(localized: "setSyncContact") }
    /// Set Taking Medicine Reminder Event Code
    static var setTakingMedicineReminder: String { String(localized: "setTakingMedicineReminder") }
    /// Set Night-time Temperature Switch Event Code
    static var setTemperatureSwitch: String { String(localized: "setTemperatureSwitch") }
    /// Set Unit event number
    static var setUnit: String { String(localized: "setUnit") }
    /// Unread message reminder switch event number
    static var setUnreadAppReminder: String { String(localized: "setUnreadAppReminder") }
    /// Raise-to-wake gesture event number
    static var setUpHandGesture: String { String(localized: "setUpHandGesture") }
    /// Set user information
    static var setUserInfo: String { String(localized: "setUserInfo") }
    /// Set Environmental Noise Volume On/Off and Threshold Event
    static var setV3Noise: String { String(localized: "setV3Noise") }
    /// Set Voice Assistant On/Off
    static var setVoiceAssistantOnOff: String { String(localized: "setVoiceAssistantOnOff") }
    /// Set walk reminder
    static var setWalkRemind: String { String(localized: "setWalkRemind") }
    /// Set multiple walk reminder times event number
    static var setWalkRemindTimes: String { String(localized: "setWalkRemindTimes") }
    /// Set watch face event number
    static var setWatchDial: String { String(localized: "setWatchDial") }
    /// Set watch dial sort event
    static var setWatchDialSort: String { String(localized: "setWatchDialSort") }
    /// Set Watch Face
    static var setWatchFaceData: String { String(localized: "setWatchFaceData") }
    /// Set weather city name event number
    static var setWeatherCityName: String { String(localized: "setWeatherCityName") }
    /// Set sunrise and sunset time event number
    static var setWeatherSunTime: String { String(localized: "setWeatherSunTime") }
    /// Set weather switch event number
    static var setWeatherSwitch: String { String(localized: "setWeatherSwitch") }
    /// Send the v3 weather protocol event number under v3
    static var setWeatherV3: String { String(localized: "setWeatherV3") }
    /// v3 set v3 world time
    static var setWorldTimeV3: String { String(localized: "setWorldTimeV3") }

    // MARK: - Sports Types
    /// BMX
    static var bMX: String { String(localized: "BMX") }
    /// aerobics
    static var aerobics: String { String(localized: "aerobics") }
    /// archery
    static var archery: String { String(localized: "archery") }
    /// badminton
    static var badminton: String { String(localized: "badminton") }
    /// ballet
    static var ballet: String { String(localized: "ballet") }
    /// barbell
    static var barbell: String { String(localized: "barbell") }
    /// baseball
    static var baseball: String { String(localized: "baseball") }
    /// basketball
    static var basketball: String { String(localized: "basketball") }
    /// biathlon
    static var biathlon: String { String(localized: "biathlon") }
    /// billiards
    static var billiards: String { String(localized: "billiards") }
    /// bowling
    static var bowling: String { String(localized: "bowling") }
    /// boxing
    static var boxing: String { String(localized: "boxing") }
    /// calisthenics
    static var calisthenics: String { String(localized: "calisthenics") }
    /// cricket
    static var cricket: String { String(localized: "cricket") }
    /// curling
    static var curling: String { String(localized: "curling") }
    /// dancing
    static var dancing: String { String(localized: "dancing") }
    /// darts
    static var darts: String { String(localized: "darts") }
    /// dodgeball
    static var dodgeball: String { String(localized: "dodgeball") }
    /// dumbbells
    static var dumbbells: String { String(localized: "dumbbells") }
    /// fencing
    static var fencing: String { String(localized: "fencing") }
    /// fishing
    static var fishing: String { String(localized: "fishing") }
    /// fitness
    static var fitness: String { String(localized: "fitness") }
    /// football
    static var football: String { String(localized: "football") }
    /// free training
    static var freeTraining: String { String(localized: "free training") }
    /// frisbee
    static var frisbee: String { String(localized: "frisbee") }
    /// golf
    static var golf: String { String(localized: "golf") }
    /// gym
    static var gym: String { String(localized: "gym") }
    /// gymnastics
    static var gymnastics: String { String(localized: "gymnastics") }
    /// handball
    static var handball: String { String(localized: "handball") }
    /// high knees
    static var highKnees: String { String(localized: "high knees") }
    /// hike
    static var hike: String { String(localized: "hike") }
    /// hip-hop
    static var hipHop: String { String(localized: "hip-hop") }
    /// hockey
    static var hockey: String { String(localized: "hockey") }
    /// karate
    static var karate: String { String(localized: "karate") }
    /// kayak
    static var kayak: String { String(localized: "kayak") }
    /// kickboxing
    static var kickboxing: String { String(localized: "kickboxing") }
    /// motorboat
    static var motorboat: String { String(localized: "motorboat") }
    /// other activity
    static var otherActivity: String { String(localized: "other activity") }
    /// outdoor Fun
    static var outdoorFun: String { String(localized: "outdoor Fun") }
    /// parkour
    static var parkour: String { String(localized: "parkour") }
    /// pilates
    static var pilates: String { String(localized: "pilates") }
    /// plank
    static var plank: String { String(localized: "plank") }
    /// pull ups
    static var pullUps: String { String(localized: "pull ups") }
    /// push-ups
    static var pushUps: String { String(localized: "push-ups") }
    /// rafting
    static var rafting: String { String(localized: "rafting") }
    /// ride
    static var ride: String { String(localized: "ride") }
    /// rowing
    static var rowing: String { String(localized: "rowing") }
    /// rugby
    static var rugby: String { String(localized: "rugby") }
    /// run
    static var run: String { String(localized: "run") }
    /// sailing
    static var sailing: String { String(localized: "sailing") }
    /// shuttlecock
    static var shuttlecock: String { String(localized: "shuttlecock") }
    /// sit-ups
    static var sitUps: String { String(localized: "sit-ups") }
    /// skateboarding
    static var skateboarding: String { String(localized: "skateboarding") }
    /// skiing
    static var skiing: String { String(localized: "skiing") }
    /// sled
    static var sled: String { String(localized: "sled") }
    /// softball
    static var softball: String { String(localized: "softball") }
    /// spinning
    static var spinning: String { String(localized: "spinning") }
    /// squash
    static var squash: String { String(localized: "squash") }
    /// squats
    static var squats: String { String(localized: "squats") }
    /// surfing
    static var surfing: String { String(localized: "surfing") }
    /// swim
    static var swim: String { String(localized: "swim") }
    /// taekwondo
    static var taekwondo: String { String(localized: "taekwondo") }
    /// tai chi
    static var taiChi: String { String(localized: "tai chi") }
    /// tennis
    static var tennis: String { String(localized: "tennis") }
    /// treadmill
    static var treadmill: String { String(localized: "treadmill") }
    /// volleyball
    static var volleyball: String { String(localized: "volleyball") }
    /// walk
    static var walk: String { String(localized: "walk") }
    /// windsurfing
    static var windsurfing: String { String(localized: "windsurfing") }
    /// yoga
    static var yoga: String { String(localized: "yoga") }
    /// zumba
    static var zumba: String { String(localized: "zumba") }

    // MARK: - Metrics Categories
    /// Cadence
    static var cadenceFull: String { String(localized: "Cadence") }
    /// Elevation
    static var elevationFull: String { String(localized: "Elevation") }
    /// Pace
    static var paceFull: String { String(localized: "Pace") }
    /// Power
    static var powerFull: String { String(localized: "Power") }
    /// Speed
    static var speedFull: String { String(localized: "Speed") }
    /// cadence
    static var cadence: String { String(localized: "cadence") }
    /// distance
    static var distance: String { String(localized: "distance") }
    /// elevation
    static var elevation: String { String(localized: "elevation") }
    /// heartRate
    static var heartRateFull: String { String(localized: "heartRate") }
    /// other
    static var otherSport: String { String(localized: "other") }
    /// overall ResponseTime
    static var overallResponseTimeFull: String { String(localized: "overallResponseTime") }
    /// pace
    static var pace: String { String(localized: "pace") }
    /// power
    static var power: String { String(localized: "power") }
    /// running Economy
    static var runningEconomy: String { String(localized: "runningEconomy") }
    /// running Fitness
    static var runningFitness: String { String(localized: "runningFitness") }
    /// speed
    static var speed: String { String(localized: "speed") }
    /// time
    static var time: String { String(localized: "time") }

    // MARK: - Metric Names
    /// Activity Time
    static var activityTime: String { String(localized: "Activity Time") }
    /// Aerobic Training Effect
    static var aerobicTrainingEffect: String { String(localized: "Aerobic Training Effect") }
    /// Anaerobic Training Efect
    static var anaerobicTrainingEfect: String { String(localized: "Anaerobic Training Efect") }
    /// Average Cadence
    static var averageCadence: String { String(localized: "Average Cadence") }
    /// Average Effort Pace
    static var averageEffortPace: String { String(localized: "Average Effort Pace") }
    /// Average Heart Rate
    static var averageHeartRate: String { String(localized: "Average Heart Rate") }
    /// Average Pace
    static var averagePace: String { String(localized: "Average Pace") }
    /// Average Power
    static var averagePower: String { String(localized: "Average Power") }
    /// Average Speed
    static var averageSpeed: String { String(localized: "Average Speed") }
    /// Average Stride Length
    static var averageStrideLength: String { String(localized: "Average Stride Length") }
    /// Average Vertical Speed
    static var averageVerticalSpeed: String { String(localized: "Average Vertical Speed") }
    /// Battery Level
    static var batteryLevel: String { String(localized: "Battery Level") }
    /// Battery Life Based On Soc
    static var batteryLifeBasedOnSoc: String { String(localized: "Battery Life Based On Soc") }
    /// Calorie
    static var calorie: String { String(localized: "Calorie") }
    /// Current Lap Distance
    static var currentLapDistance: String { String(localized: "Current Lap Distance") }
    /// Current Time
    static var currentTime: String { String(localized: "Current Time") }
    /// Effort Pace
    static var effortPace: String { String(localized: "Effort Pace") }
    /// Grade
    static var grade: String { String(localized: "Grade") }
    /// Heart Rate
    static var heartRate: String { String(localized: "Heart Rate") }
    /// Heart Rate Reserve
    static var heartRateReserve: String { String(localized: "Heart Rate Reserve") }
    /// Heart Rate Zone
    static var heartRateZone: String { String(localized: "Heart Rate Zone") }
    /// Lap Ascent
    static var lapAscent: String { String(localized: "Lap Ascent") }
    /// Lap Cadence
    static var lapCadence: String { String(localized: "Lap Cadence") }
    /// Lap Descent
    static var lapDescent: String { String(localized: "Lap Descent") }
    /// Lap Effort Pace
    static var lapEffortPace: String { String(localized: "Lap Effort Pace") }
    /// Lap Heart Rate
    static var lapHeartRate: String { String(localized: "Lap Heart Rate") }
    /// Lap Pace
    static var lapPace: String { String(localized: "Lap Pace") }
    /// Lap Power
    static var lapPower: String { String(localized: "Lap Power") }
    /// Lap Speed
    static var lapSpeed: String { String(localized: "Lap Speed") }
    /// Lap Strido Length
    static var lapStridoLength: String { String(localized: "Lap Strido Length") }
    /// Lap Time
    static var lapTime: String { String(localized: "Lap Time") }
    /// Lap Vertical Speed
    static var lapVerticalSpeed: String { String(localized: "Lap Vertical Speed") }
    /// Last Lap Ascent
    static var lastLapAscent: String { String(localized: "Last Lap Ascent") }
    /// Last Lap Cadence
    static var lastLapCadence: String { String(localized: "Last Lap Cadence") }
    /// Last Lap Descent
    static var lastLapDescent: String { String(localized: "Last Lap Descent") }
    /// Last Lap Distance
    static var lastLapDistance: String { String(localized: "Last Lap Distance") }
    /// Last Lap Heart Rate
    static var lastLapHeartRate: String { String(localized: "Last Lap Heart Rate") }
    /// Last Lap Pace
    static var lastLapPace: String { String(localized: "Last Lap Pace") }
    /// Last Lap Speed
    static var lastLapSpeed: String { String(localized: "Last Lap Speed") }
    /// Last Lap Time
    static var lastLapTime: String { String(localized: "Last Lap Time") }
    /// Maximum Speed
    static var maximumSpeed: String { String(localized: "Maximum Speed") }
    /// Overall Response Time
    static var overallResponseTime: String { String(localized: "Overall Response Time") }
    /// Stride Length
    static var strideLength: String { String(localized: "Stride Length") }
    /// Total Ascent
    static var totalAscent: String { String(localized: "Total Ascent") }
    /// Total Descent
    static var totalDescent: String { String(localized: "Total Descent") }
    /// Total Distance
    static var totalDistance: String { String(localized: "Total Distance") }
    /// Total Time
    static var totalTime: String { String(localized: "Total Time") }
    /// Training Load
    static var trainingLoad: String { String(localized: "Training Load") }
    /// Vertical Speed
    static var verticalSpeed: String { String(localized: "Vertical Speed") }
    /// Vo2max
    static var vo2max: String { String(localized: "Vo2max") }
    /// power30sAveragePower
    static var power30sAveragePower: String { String(localized: "power30sAveragePower") }

    // MARK: - Other
    /// Cross country running
    static var crossCountryRunning: String { String(localized: "Cross country running") }
    static var mon28: String { String(localized: "MON 28") }
    /// Max Heart Rate
    static var maxHeartRate: String { String(localized: "Max Heart Rate") }
    static var selectFromAlbum: String { String(localized: "Select from album") }
    static var selectPhoto: String { String(localized: "Select photo") }
    /// Time To Sunrise Sunset
    static var timeToSunriseSunset: String { String(localized: "Time To Sunrise Sunset") }
    /// Track and field
    static var trackAndField: String { String(localized: "Track and field") }
    static var using: String { String(localized: "Using") }
    /// alpine skiing
    static var alpineSkiing: String { String(localized: "alpine skiing") }
    /// beach soccer
    static var beachSoccer: String { String(localized: "beach soccer") }
    /// bungee jumping
    static var bungeeJumping: String { String(localized: "bungee jumping") }
    /// climbing machine
    static var climbingMachine: String { String(localized: "climbing machine") }
    /// core training
    static var coreTraining: String { String(localized: "core training") }
    /// cross training
    static var crossTraining: String { String(localized: "cross training") }
    /// cross-country skiing
    static var crossCountrySkiing: String { String(localized: "cross-country skiing") }
    /// dragon boat
    static var dragonBoat: String { String(localized: "dragon boat") }
    /// elliptical machine
    static var ellipticalMachine: String { String(localized: "elliptical machine") }
    /// functional strength training
    static var functionalStrengthTraining: String { String(localized: "functional strength training") }
    /// high-intensity interval training
    static var highIntensityIntervalTraining: String { String(localized: "high-intensity interval training") }
    /// horizontal bar
    static var horizontalBar: String { String(localized: "horizontal bar") }
    /// horseback riding
    static var horsebackRiding: String { String(localized: "horseback riding") }
    /// ice hockey
    static var iceHockey: String { String(localized: "ice hockey") }
    /// indoor cycling
    static var indoorCycling: String { String(localized: "indoor cycling") }
    /// indoor rowing
    static var indoorRowing: String { String(localized: "indoor rowing") }
    /// indoor running
    static var indoorRunning: String { String(localized: "indoor running") }
    /// indoor walking
    static var indoorWalking: String { String(localized: "indoor walking") }
    /// jumping jacks
    static var jumpingJacks: String { String(localized: "jumping jacks") }
    /// kite flying
    static var kiteFlying: String { String(localized: "kite flying") }
    /// martial arts
    static var martialArts: String { String(localized: "martial arts") }
    /// mountain climbing
    static var mountainClimbing: String { String(localized: "mountain climbing") }
    /// open water swimming
    static var openWaterSwimming: String { String(localized: "open water swimming") }
    /// organize and relax
    static var organizeAndRelax: String { String(localized: "organize and relax") }
    /// outdoor cycling
    static var outdoorCycling: String { String(localized: "outdoor cycling") }
    /// outdoor running
    static var outdoorRunning: String { String(localized: "outdoor running") }
    /// outdoor walking
    static var outdoorWalking: String { String(localized: "outdoor walking") }
    /// parallel bar
    static var parallelBar: String { String(localized: "parallel bar") }
    /// pool swimming
    static var poolSwimming: String { String(localized: "pool swimming") }
    /// Request firmware algorithm file information (ACC/GPS)
    static var requestAlgFile: String { String(localized: "requestAlgFile") }
    /// rock climbing
    static var rockClimbing: String { String(localized: "rock climbing") }
    /// roller skating
    static var rollerSkating: String { String(localized: "roller skating") }
    /// rope skipping
    static var ropeSkipping: String { String(localized: "rope skipping") }
    /// rowing machine
    static var rowingMachine: String { String(localized: "rowing machine") }
    /// sepak takraw
    static var sepakTakraw: String { String(localized: "sepak takraw") }
    /// snow sports
    static var snowSports: String { String(localized: "snow sports") }
    /// snowboard
    static var snowboard: String { String(localized: "snowboard") }
    /// snowmobile
    static var snowmobile: String { String(localized: "snowmobile") }
    /// social dance
    static var socialDance: String { String(localized: "social dance") }
    /// square dance
    static var squareDance: String { String(localized: "square dance") }
    /// stair climbing
    static var stairClimbing: String { String(localized: "stair climbing") }
    /// table tennis
    static var tableTennis: String { String(localized: "table tennis") }
    /// traditional strength training
    static var traditionalStrengthTraining: String { String(localized: "traditional strength training") }
    /// treadmills
    static var treadmills: String { String(localized: "treadmills") }
    /// walking machine
    static var walkingMachine: String { String(localized: "walking machine") }
    /// water polo
    static var waterPolo: String { String(localized: "water polo") }
    /// weight lifting
    static var weightLifting: String { String(localized: "weight lifting") }
    /// Import ZIP file
    static var 导入ZIP文件: String { String(localized: "导入ZIP文件") }
    /// Confrim
    static var 确定: String { String(localized: "确定") }
    /// Dial Customization Tool
    static var 表盘定制工具: String { String(localized: "表盘定制工具") }
}

// MARK: - String Extension

extension String {
    /// Localizes the string using the current locale.
    /// The string itself is used as the localization key.
    /// Compatible with iOS 15+
    var i18n: String {
        Bundle.main.localizedString(forKey: self, value: nil, table: nil)
    }
}
