# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# Comment the next line if you don't want to use dynamic frameworks
source 'https://cdn.cocoapods.org/'
use_frameworks!
inhibit_all_warnings!

target 'IDODemoFull' do

end

target 'IDODemoLite'  do

end

pod 'SnapKit'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SVProgressHUD'
pod 'ReachabilitySwift'
pod 'SSZipArchive'
pod 'ZIPFoundation', '~> 0.9.11'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
